name: main
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    name: Build and test
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Cypress.io
        uses: cypress-io/github-actions@v2.9.7
        with:
          browser: chrome