name: main
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Cypress.io
        uses: cypress-io/github-actions@v2.9.7
        with:
          browser: chrome
